name: Tinnitussaurus
options:
  bundleIdPrefix: com.paulabac
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "5.0.0"

configFiles:
  Debug: Debug.xcconfig
  Release: Release.xcconfig

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  Tinnitussaurus:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tinnitussaurus
        excludes:
          - "Preview Content/**"
    resources:
      - path: Tinnitussaurus/Resources/Assets.xcassets
      - path: Tinnitussaurus/Resources/Fonts
      - path: Tinnitussaurus/PrivacyInfo.xcprivacy
    info:
      path: Tinnitussaurus/Info.plist
      properties:
        CFBundleDisplayName: Tinnitussaurus
        LSApplicationCategoryType: public.app-category.healthcare-fitness
        UIBackgroundModes: [audio]
        UILaunchScreen: {}
        UIFileSharingEnabled: true
        UIAppFonts:
          - SpaceGrotesk-Regular.ttf
          - SpaceGrotesk-Medium.ttf
          - SpaceGrotesk-SemiBold.ttf
          - SpaceGrotesk-Bold.ttf
          - Inter-Regular.ttf
        LSSupportsOpeningDocumentsInPlace: true
        NSUserNotificationsUsageDescription: "Tinnitussaurus sends daily reminders to help you maintain a consistent therapy routine."
        RevenueCatAPIKey: $(REVENUECAT_API_KEY)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitussaurus
        SWIFT_STRICT_CONCURRENCY: complete
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: RevenueCat
        product: RevenueCat
    entitlements:
      path: Tinnitussaurus/Tinnitussaurus.entitlements
      properties:
        com.apple.developer.healthkit: false

  TinnitussaurusTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TinnitussaurusTests
    dependencies:
      - target: Tinnitussaurus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitussaurus.tests
        GENERATE_INFOPLIST_FILE: YES

  TinnitussaurusUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TinnitussaurusUITests
    dependencies:
      - target: Tinnitussaurus
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitussaurus.uitests
        GENERATE_INFOPLIST_FILE: YES
