/**
 * Export Manager - Generate and share therapy progress reports
 * Creates CSV reports from journal and session data for sharing with doctors
 */

class ExportManager {
    constructor(app) {
        this.app = app;
    }

    /**
     * Generate a CSV report of journal entries
     */
    generateJournalCSV() {
        const entries = this.getJournalEntries();
        if (entries.length === 0) return null;

        const headers = ['Date', 'Severity (1-10)', 'Notes', 'Tags'];
        const rows = entries.map(e => [
            new Date(e.date).toLocaleDateString(),
            e.severity,
            `"${(e.notes || '').replace(/"/g, '""')}"`,
            `"${(e.tags || []).join(', ')}"`
        ]);

        return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    }

    /**
     * Generate a CSV report of therapy sessions
     */
    generateSessionCSV() {
        const sessions = this.getSessionData();
        if (sessions.length === 0) return null;

        const headers = ['Date', 'Duration (min)', 'Type', 'Frequency (Hz)'];
        const rows = sessions.map(s => [
            new Date(s.date).toLocaleDateString(),
            Math.round(s.duration / 60000),
            s.type || 'therapy',
            s.frequency || ''
        ]);

        return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    }

    /**
     * Generate a combined text report
     */
    generateTextReport() {
        const entries = this.getJournalEntries();
        const stats = this.app.sessionManager?.getStats();
        const matchedFreq = this.app.matchedFrequencies;

        let report = '';
        report += '═══════════════════════════════════════\n';
        report += '  TINNITUSSAURUS - Progress Report\n';
        report += '═══════════════════════════════════════\n';
        report += `  Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n\n`;

        // Matched frequency
        report += '── Matched Frequency ──\n';
        if (matchedFreq?.left || matchedFreq?.right) {
            if (matchedFreq.left) report += `  Left ear:  ${matchedFreq.left} Hz\n`;
            if (matchedFreq.right) report += `  Right ear: ${matchedFreq.right} Hz\n`;
        } else {
            report += '  Not yet calibrated\n';
        }
        report += '\n';

        // Session summary
        report += '── Session Summary ──\n';
        if (stats) {
            report += `  Today:      ${stats.todayTimeFormatted}\n`;
            report += `  This week:  ${stats.weekTimeFormatted}\n`;
            report += `  All time:   ${stats.totalTimeFormatted}\n`;
            report += `  Streak:     ${stats.streak} day(s)\n`;
        } else {
            report += '  No session data\n';
        }
        report += '\n';

        // Journal entries
        report += '── Journal Entries (Last 30 days) ──\n';
        if (entries.length === 0) {
            report += '  No entries recorded\n';
        } else {
            const recent = entries.slice(0, 30);
            const avgSeverity = recent.reduce((sum, e) => sum + e.severity, 0) / recent.length;
            report += `  Entries: ${recent.length}  |  Avg severity: ${avgSeverity.toFixed(1)}/10\n\n`;

            recent.forEach(e => {
                const date = new Date(e.date).toLocaleDateString();
                report += `  ${date}  Severity: ${e.severity}/10`;
                if (e.notes) report += `  "${e.notes}"`;
                if (e.tags?.length) report += `  [${e.tags.join(', ')}]`;
                report += '\n';
            });
        }

        report += '\n═══════════════════════════════════════\n';
        report += '  Generated by Tinnitussaurus\n';
        report += '  This is not a medical document.\n';
        report += '═══════════════════════════════════════\n';

        return report;
    }

    /**
     * Share the report using Web Share API or download as file
     */
    async shareReport(format = 'text') {
        let content, filename, mimeType;

        if (format === 'csv-journal') {
            content = this.generateJournalCSV();
            filename = `tinnitus-journal-${this.dateStamp()}.csv`;
            mimeType = 'text/csv';
        } else if (format === 'csv-sessions') {
            content = this.generateSessionCSV();
            filename = `tinnitus-sessions-${this.dateStamp()}.csv`;
            mimeType = 'text/csv';
        } else {
            content = this.generateTextReport();
            filename = `tinnitus-report-${this.dateStamp()}.txt`;
            mimeType = 'text/plain';
        }

        if (!content) {
            alert('No data to export.');
            return;
        }

        const blob = new Blob([content], { type: mimeType });
        const file = new File([blob], filename, { type: mimeType });

        // Try Web Share API first
        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            try {
                await navigator.share({
                    title: 'Tinnitussaurus Progress Report',
                    text: 'My tinnitus therapy progress report',
                    files: [file]
                });
                return;
            } catch (err) {
                if (err.name === 'AbortError') return; // User cancelled
            }
        }

        // Fallback: download file
        this.downloadFile(content, filename, mimeType);
    }

    downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    /**
     * Show export options modal
     */
    showExportModal() {
        document.getElementById('exportModal')?.remove();

        const modal = document.createElement('div');
        modal.id = 'exportModal';
        modal.className = 'export-modal';
        modal.innerHTML = `
            <div class="export-modal-content">
                <button class="export-close" id="exportClose">&times;</button>
                <h3>Export Progress Report</h3>
                <p class="export-desc">Share your therapy progress with your healthcare provider.</p>
                <div class="export-options">
                    <button class="export-option" data-format="text">
                        <span class="export-opt-icon">📄</span>
                        <span class="export-opt-label">Full Report (Text)</span>
                    </button>
                    <button class="export-option" data-format="csv-journal">
                        <span class="export-opt-icon">📊</span>
                        <span class="export-opt-label">Journal Data (CSV)</span>
                    </button>
                    <button class="export-option" data-format="csv-sessions">
                        <span class="export-opt-icon">⏱️</span>
                        <span class="export-opt-label">Session Data (CSV)</span>
                    </button>
                </div>
            </div>
        `;
        document.body.appendChild(modal);
        requestAnimationFrame(() => modal.classList.add('open'));

        document.getElementById('exportClose').addEventListener('click', () => {
            modal.classList.remove('open');
            setTimeout(() => modal.remove(), 300);
        });

        modal.querySelectorAll('.export-option').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const format = e.currentTarget.dataset.format;
                this.shareReport(format);
                modal.classList.remove('open');
                setTimeout(() => modal.remove(), 300);
            });
        });
    }

    // -- Data Access Helpers --

    getJournalEntries() {
        try {
            const data = localStorage.getItem('tinnitusJournalEntries');
            return data ? JSON.parse(data) : [];
        } catch {
            return [];
        }
    }

    getSessionData() {
        try {
            const data = localStorage.getItem('tinnitusSessionHistory');
            return data ? JSON.parse(data) : [];
        } catch {
            return [];
        }
    }

    dateStamp() {
        const d = new Date();
        return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
    }
}
export { ExportManager };
