name: TinnitusReliefPro
options:
  bundleIdPrefix: com.paulabac
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true

packages:
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "5.0.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  TinnitusReliefPro:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TinnitusReliefPro
        excludes:
          - "Preview Content/**"
    resources:
      - path: TinnitusReliefPro/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitusreliefpro
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIBackgroundModes: audio
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Tinnitus Relief"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.healthcare-fitness"
        SWIFT_STRICT_CONCURRENCY: complete
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: RevenueCat
        product: RevenueCat
    entitlements:
      path: TinnitusReliefPro/TinnitusReliefPro.entitlements
      properties:
        com.apple.developer.healthkit: false

  TinnitusReliefProTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TinnitusReliefProTests
    dependencies:
      - target: TinnitusReliefPro
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitusreliefpro.tests

  TinnitusReliefProUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TinnitusReliefProUITests
    dependencies:
      - target: TinnitusReliefPro
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.paulabac.tinnitusreliefpro.uitests
